server:
  port: 8083
  context-path: /

security:
  oauth2:
    client:
      client-id: client2
      client-secret: client2_secret
      user-authorization-uri: http://localhost:8081/oauth/authorize
      access-token-uri: http://localhost:8081/oauth/token
    resource:
      user-info-uri: http://localhost:8081/oauth/user